#!/usr/bin/env python3
"""
Usage:
       jst --help
       jst init BRANCH_CE BRANCH_PRO [SVN_USER] [options]
       jst (build|bd) [DIR] [--test] [options]
       jst deploy [DIR] [options]
       jst (start|stop|restart|ps|log|go|status|update|diff|revert|init-db) [options]
       jst svn SVN_ARGS...
       jst configure --db=<db> [options]

Options:
    --env=<env>      Environment
    --verbose        Verbose output

Commands:
    init        checkout ce and pro source code and configure buildomatic
    build       build jrs (run tests if --test is specified)
    deploy      deploy jrs to tomcat
    bd          run build and deploy in one command (run tests if --test is specified)
    start       start tomcat
    stop        stop tomcat
    restart     restart tomcat
    ps          show tomcat process info
    log         print tomcat catalina.out
    go          open app in default web browser
    status      run 'svn status' against both source trees
    update      run 'svn update' against both source trees
    diff        run 'svn diff' against source trees
    revert      run 'svn revert -R' against both source trees
    svn         run arbitrary svn command against both source trees
    configure   change default_master.properties according to parameters
    init-db     create jasperserver, foodmart and sugarcm databases

Examples:
    jst init anonymous branches/bugfix branches/bugfix-pro
    jst init anonymous trunk trunk
    jst build ce/jasperserver-war
"""

import distutils.dir_util
import fileinput
import glob
import os
import psutil
import shutil
import socket
import subprocess
import sys
import textwrap
import time
import traceback
import urllib.request

import docopt


_tomcat_ver = "7.0.64"

def main(args):

    # check if we are in the right directory
    if (not args["init"] and not args["go"]):
        assert_initialized()

    if (args["init"]):
        cmd_init(args["BRANCH_CE"], args["BRANCH_PRO"], args["SVN_USER"])
    # ant/buildomatic commands
    elif (args["build"]):
        cmd_build(args["DIR"], args["--test"])
    elif (args["deploy"]):
        cmd_deploy(args["DIR"])
    elif (args["bd"]):
        cmd_build(args["DIR"], args["--test"])
        cmd_deploy(args["DIR"])
    # tomcat commands
    elif (args["start"]):
        cmd_start()
    elif (args["stop"]):
        cmd_stop()
    elif (args["restart"]):
        cmd_stop()
        cmd_start()
    elif (args["ps"]):
        cmd_ps()
    elif (args["log"]):
        cmd_log()
    # svn commands
    elif (args["status"]):
        run_svn_command(["status"])
    elif (args["update"]):
        run_svn_command(["update"])
    elif (args["diff"]):
        run_svn_command(["diff"])
    elif (args["revert"]):
        cmd_revert()
    elif (args["svn"]):
        run_svn_command(args["SVN_ARGS"])
    # misc commands
    elif (args["go"]):
        cmd_go()
    elif (args["configure"]):
        cmd_configure(args["--db"])
    elif (args["init-db"]):
        cmd_init_db()
    else:
        raise ValueError("Unknown arguments:\n" + str(args))


def cmd_init(branch_ce, branch_pro, svn_user):
    """checkout source and configure buildomatic"""
    if (not svn_user):
        svn_user = "anonymous"

    svn_checkout(branch_ce, branch_pro, svn_user)
    configure_buildomatic("pg") # postgres is default db
    # only devs need sources so no need to tweak under any other environment
    if (env == "dev"):
        tweak_buildomatic_for_dev_env()


def cmd_build(directory, run_tests):
    if (env == "dev"):
        ensure_tomcat()

    args = ["ant", "-buildfile", ce_dir + "/buildomatic/build.xml"]

    if (directory):

        directory = format_path(directory)

        if (directory.startswith("ce/")):
            args += ["build-dir-ce", "-DdirName=" + directory[3:]]
        elif (directory.startswith("pro/")):
            args += ["build-dir-pro", "-DdirName=" + directory[4:]]
        else:
            raise ValueError("Unknown directory: " + directory)
    else:
        args += ["build-src-all"]

    if (not run_tests):
        args += ["-DSKIP_TEST_ARG=skipTests"]

    changed_env = ensure_java7()
    log_info("Building")
    subprocess.check_call(args, env=changed_env, stdout=subprocess_stdout)


def ensure_java7():
    # cannot compile with java 8
    process_env = os.environ.copy()
    # check if we have java 7 already
    if ("JAVA_HOME" not in process_env or not is_java7(process_env["JAVA_HOME"] + "/bin/java")):
        # a guess
        process_env["JAVA_HOME"] = "/usr/lib/jvm/java-7-oracle"
        log_info("Looking for java 7")
    # check again
    if (not is_java7(process_env["JAVA_HOME"] + "/bin/java")):
        raise IOError("java 7 is required to build source")

    return process_env

def is_java7(java_binary):
    java_output = subprocess.check_output([java_binary, "-version"],
                                          universal_newlines=True,
                                          stderr=subprocess.STDOUT)
    return ('java version "1.7.' in java_output)


def cmd_deploy(directory):
    if (env == "dev"):
        ensure_tomcat()

    if (directory):

        directory = format_path(directory)

        if (directory.endswith("-war")):
            raise ValueError("WAR deployment is not supported")

        source = os.getcwd() + "/" + directory + "/target/*.jar"
        files = glob.glob(source)
        destination = tomcat_home + "/webapps/jasperserver-pro/WEB-INF/lib/"
        deployed = False

        for file in files:
            if (not file.endswith("sources.jar")):
                shutil.copy(file, destination)
                log_info("Deployed: " + file)
                deployed = True

        if (not deployed):
            raise IOError("Nothing to deploy at: " + source)
    else:
        args = ["ant", "-buildfile", ce_dir + "/buildomatic/build.xml", "deploy-webapp-pro"]
        log_info("Deploying")
        subprocess.check_call(args, stdout=subprocess_stdout)


def format_path(directory):
    if (directory.endswith("/")):
        directory = directory[:-1]
    return directory


def cmd_start():
    pids = get_tomcat_pids()
    if (pids):
        log_info("Already running; pid(s): " + ", ".join(pids))
        return

    check_db()
    log_info("Starting tomcat")
    execute_catalina_action("start")
    cmd_ps()


def cmd_stop():
    pids = get_tomcat_pids()
    if (pids):
        stop_gracefully(30)
        pids = get_tomcat_pids()
        if (pids):
            log_warning("Unable to stop gracefully")
            for pid in pids:
                log_warning("killing process with pid " + pid)
                psutil.Process(int(pid)).kill()

    cmd_ps()


def cmd_ps():
    pids = get_tomcat_pids()
    if (pids):
        log_info("pid(s): " + ", ".join(pids))
    else:
        log_info("tomcat is down")


def cmd_log():
    with open(tomcat_home + "/logs/catalina.out", 'r') as fin:
        print(fin.read())


def cmd_revert():
    # always print results even if verbose=False
    subprocess.check_call(["svn", "revert", ce_dir, "-R"])
    subprocess.check_call(["svn", "revert", pro_dir, "-R"])


def cmd_go():
    pids = get_tomcat_pids()
    if (pids):
        subprocess.check_call(["xdg-open", "http://localhost:8080/jasperserver-pro"],
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        cmd_ps()


def cmd_configure(db):
    configure_buildomatic(db)


def cmd_init_db():
    log_info("Initializing db")
    subprocess.check_call(["ant",
                     "create-js-db",
                     "build-js-ddl-pro",
                     "init-js-db-pro",
                     "create-sugarcrm-db",
                     "load-sugarcrm-db",
                     "create-foodmart-db",
                     "load-foodmart-db",
                     "update-foodmart-db",
                     "run-production-data-pro"],
                          cwd=ce_dir + "/buildomatic", stdout=subprocess_stdout)


def assert_initialized():
    if (not os.path.isdir(ce_dir) or not os.path.isdir(pro_dir)):
        raise IOError("Cannot find ce and pro directories. Did you run init?")


def run_svn_command(svn_args):
    subprocess.check_call(["svn"] + svn_args + [ce_dir])
    subprocess.check_call(["svn"] + svn_args + [pro_dir])


def stop_gracefully(timeout):
    execute_catalina_action("stop")
    log_info("Stopping tomcat")
    #sys.stdout.write("Waiting for tomcat to stop")
    sys.stdout.flush()
    elapsed = 0 # number of seconds since shutdown initiated
    while (get_tomcat_pids() and elapsed <= timeout):
        time.sleep(1)
        elapsed += 1
        sys.stdout.write(".")
        sys.stdout.flush()

    print()


def get_tomcat_pids():
    catalina_main_class_arg = "org.apache.catalina.startup.Bootstrap"
    catalina_home_arg = "-Dcatalina.home=" + tomcat_home
    pids = []

    for proc in psutil.process_iter():
        if (proc.name() == "java" \
                and catalina_main_class_arg in proc.cmdline() \
                and catalina_home_arg in proc.cmdline()):
            pids.append(str(proc.pid))
            # keep looking, might be multiple instances running

    return pids


def svn_checkout(branch_ce, branch_pro, svn_user):
    """checkout source"""
    svn_url_prefix = "https://" + svn_user + "@svnserver.jaspersoft.com/jasperserver"

    if (branch_ce.startswith("https://")):
        url_ce = branch_ce
    else:
        url_ce = svn_url_prefix + "/" + normalize_branch_name(branch_ce)

    if (branch_pro.startswith("https://")):
        url_pro = branch_pro
    else:
        url_pro = svn_url_prefix + "-pro/" + normalize_branch_name(branch_pro)

    log_info("Checking out '" + url_ce + "' into 'ce'")
    subprocess.check_call(["svn", "checkout", url_ce, "ce"], stdout=subprocess_stdout)
    log_info("Checking out '" + url_pro + "' into 'pro'")
    subprocess.check_call(["svn", "checkout", url_pro, "pro"], stdout=subprocess_stdout)


def normalize_branch_name(branch):
    """ensures that branch includes branches/ unless trunk"""
    if (branch != "trunk" and not branch.startswith("branches/")):
        return "branches/" + branch

    return branch;

def configure_buildomatic(db):
    log_info("Configuring buildomatic")
    check_db_type(db)
    #writes default_master.properties file
    with open(ce_dir + "/buildomatic/default_master.properties", "w") as f:
        write_app_server_section(f)
        write_db_section(f, db)
        write_source_section(f)

    if (db in ["ora"]):
        copy_buildomatic_additional(db)


def write_app_server_section(f):
    if (env == "dev"):
        f.write("appServerType = tomcat7\n")
        f.write("appServerDir = " + tomcat_home + "\n")
    else:
        f.write("appServerType = skipAppServerCheck\n")


def write_db_section(f, db):
    if (env == "dev"):
        # devs run the app and the db on the same machine
        db_host = "localhost"
    else:
        db_host = "db"

    if (db == "pg"):
        f.write("dbType = postgresql\n")
        f.write("dbHost = " + db_host + "\n")
        f.write("dbUsername = postgres\n")
        f.write("dbPassword = postgres\n")
    elif (db == "mysql"):
        f.write("dbType = mysql\n")
        f.write("dbHost = " + db_host + "\n")
        f.write("dbUsername = root\n")
        f.write("dbPassword =\n")
    elif (db == "ora"):
        f.write("dbType = oracle\n")
        f.write("dbHost = " + db_host + "\n")
        f.write("sid = xe\n")
        f.write("dbUsername = jasperserver\n")
        f.write("dbPassword = password\n")
        f.write("sysUsername = system\n")
        f.write("sysPassword = oracle\n")
    else:
        raise ValueError("Unknown db type " + db)

def check_db_type(db):
    if (db not in ["pg", "mysql", "ora"]):
        raise ValueError("Unknown db type " + db)


def write_source_section(f):
    f.write("maven = /usr/local/maven/bin/mvn\n")
    f.write("mvn-mirror=http://mvnrepo.jaspersoft.com:8081/artifactory/repo\n")
    f.write("js-path = " + ce_dir + "\n")
    f.write("js-pro-path = " + pro_dir + "\n")

def copy_buildomatic_additional(db):
    copy(pro_dir + "/buildomatic-additional", ce_dir + "/buildomatic")
    raise ValueError("test")


def copy(src, dst):
    distutils.dir_util.copy_tree(src, dst)


def tweak_buildomatic_for_dev_env():
    """makes maven install sources into local repository"""
    searchString = '<arg value="clean"/>'
    for line in fileinput.input(ce_dir + "/buildomatic/bin/dev.xml", inplace=True):
        if (line.strip() == searchString):
            line = line.replace(searchString, searchString + '<arg value="source:jar-no-fork"/>')
        print(line, end="")

def ensure_tomcat():
    download_tomcat()
    extract_tomcat()
    configure_tomcat()


def download_tomcat():
    distribution_url = "http://www.gtlib.gatech.edu/pub/apache/tomcat/tomcat-7/v" + _tomcat_ver + "/bin/apache-tomcat-" + _tomcat_ver + ".tar.gz"
    if (not os.path.isfile(tomcat_distribution_file)):
        os.makedirs(os.path.dirname(tomcat_distribution_file), exist_ok=True)
        log_info("Downloading tomcat " + _tomcat_ver + " from " + distribution_url)
        urllib.request.urlretrieve(distribution_url, tomcat_distribution_file, print_progress)
        print()


def extract_tomcat():
    if (not os.path.isdir(tomcat_home)):
        os.makedirs(tomcat_home)
        log_info("Extracting tomcat into " + tomcat_home)
        subprocess.check_call(["tar", "-xf", tomcat_distribution_file, "-C", tomcat_home, "--strip-components=1"], stdout=subprocess_stdout)


def configure_tomcat():
    with open(tomcat_home + "/bin/setenv.sh", "w") as f:
        f.write(textwrap.dedent("""
            export CATALINA_OPTS="-agentlib:jdwp=transport=dt_socket,address=1044,server=y,suspend=n -Djavax.xml.soap.SOAPFactory=org.apache.axis.soap.SOAPFactoryImpl -Djavax.xml.transform.TransformerFactory=org.apache.xalan.processor.TransformerFactoryImpl -Djavax.xml.soap.SOAPConnectionFactory=org.apache.axis.soap.SOAPConnectionFactoryImpl -Djavax.xml.soap.MessageFactory=org.apache.axis.soap.MessageFactoryImpl -Djava.net.preferIPv4Stack=true -Xms1024m -Xmx2048m -XX:PermSize=32m -XX:MaxPermSize=512m -Xss2m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
        """).strip().format(tomcat_home))


def print_progress(count, blockSize, totalSize):
    percent = int(count * blockSize * 100 / totalSize)
    sys.stdout.write("\r%3d%%" % percent)
    sys.stdout.flush()


def execute_catalina_action(action):
    subprocess.check_call([tomcat_home + "/bin/catalina.sh", action],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def check_db():
    """checks if db is up"""
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = s.connect_ex(("localhost", 5432))
    if (result != 0):
        raise IOError("DB is down")

    s.close()


def get_working_environment(args):
    if (args["--env"]):
        if (args["--env"] in env_list):
            return args["--env"]
        else:
            raise ValueError("Unknown environment " + args["--env"])
    return "dev"


def log_error(message):
    log_color(message, color.RED, color.BRIGHT)


def log_warning(message):
    log_color(message, color.YELLOW, color.BRIGHT)


def log_debug(message):
    log_color(message, color.WHITE, color.DIM)


def log_info(message):
    print(str(message))


def log_color(message, fg, style):
    print("\033[" + fg + "m" + "\033[" + style + "m" + str(message) + "\033[0m")


# working environment
env_list = ["dev", "ci"]
env = ""
tomcat_home = os.getcwd() + "/tomcat"
tomcat_distribution_file = os.path.expanduser("~") + "/.cache/jst/apache-tomcat-" + _tomcat_ver + ".tar.gz"
ce_dir = os.getcwd() + "/ce"
pro_dir = os.getcwd() + "/pro"
subprocess_stdout = subprocess.DEVNULL

class color:
    BLACK = "30"
    RED = "31"
    GREEN = "32"
    YELLOW = "33"
    BLUE = "34"
    MAGENTA = "35"
    CYAN = "36"
    WHITE = "37"
    BRIGHT = "1"
    DIM = "2"
    NORMAL = "22"
    RESET_ALL = "0"

if (__name__ == "__main__"):

    args = docopt.docopt(__doc__, version="0.1")

    if (args["--verbose"]):
        subprocess_stdout = None

    env = get_working_environment(args)

    try:
        main(args)
    except Exception as e:
        log_error(e)
        if (args["--verbose"]):
            traceback.print_exc()
        exit(1)
